### ISSUE TITLE
Progressively adapt old API routes to fastAPI

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#10889]
This is not high-priority (the old routes aren't broken and will continue to work), but it would be great if we can get as many people as possible to get their hands on this task.

An example PR to add fastAPI routes is here: https://github.com/galaxyproject/galaxy/pull/11056
We are aiming at following the [fastAPI documentation](https://fastapi.tiangolo.com/tutorial/) closely.
We will try to keep the routes as simple as possible, pushing complex logic into managers as much as possible.
Schema models may either live next to the manager code, or in lib/galaxy/schema/ for models that are used in
different parts of the app. Schema models for database models should always go to lib/galaxy/schema.

If you have any questions, please ask here or on [gitter](https://gitter.im/galaxyproject/dev) 

List of files in lib/galaxy/webapps/galaxy/api/ : 
*(To prevent duplication of effort, please put down your GitHub username next to the controller you're working on)*

- [ ] annotations.py
- [ ] authenticate.py
- [ ] cloudauthz.py
- [x] cloud.py #16296
- [x] configuration.py #11126
- [ ] container_resolution.py
- [x] dataset_collections.py #12781
- [x] datasets.py #12924
- [x] datatypes.py #11098
- [x] display_applications.py #16156
- [ ] dynamic_tools.py
- [ ] extended_metadata.py
- [x] folder_contents.py #14223
- [x] folders.py  #12131
- [ ] forms.py
- [x] genomes.py #11241
- [x] group_roles.py #12337
- [x] groups.py #17051
- [x] group_users.py #13648
- [x] histories.py #12386
- [x] history_contents.py #12578
- [x] item_tags.py #17064
- [ ] job_files.py
- [x] job_lock.py #10823
- [ ] job_ports.py
- [ ] jobs.py @mvdbeek
- [x] libraries.py #11983
- [x] library_contents.py #18838
- [ ] library_datasets.py
- [x] licenses.py #11056 
- [x] metrics.py #11568
- [ ] page_revisions.py
- [x] pages.py #11262
- [ ] plugins.py
- [ ] provenance.py
- [x] quotas.py #11315
- [x] remote_files.py #11211 
- [x] roles.py #10823
- [ ] sanitize_allow.py
- [ ] search.py
- [x] tags.py  #11224
- [x] tool_data.py #11167
- [ ] tool_dependencies.py @ic4f 
- [ ] tool_entry_points.py
- [ ] tool_shed_repositories.py
- [ ] tools.py
- [ ] toolshed.py
- [x] tours.py #11089 
- [ ] trs_consumer.py
- [ ] trs_search.py
- [ ] uploads.py
- [ ] users.py
- [ ] visualizations.py
- [ ] webhooks.py
- [ ] workflows.py #14843

**Comment by bgruening** [comment]
Can you add to this issue an example PR or some documentation? This would help to spread the word.

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/galaxy/blob/41fd63cdc66d52510546a9d58661f7f3016fcf86/lib/galaxy/webapps/galaxy/api/jobs.py#L84 is the best we have so far, I'll update this with something cleaner when we have it.
