### ISSUE TITLE
Executive summary of Q1 Backend Goals

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#11064]
- [ ] Move standard Galaxy framework to fastAPI (→ UI/UX WG)
  - [x] Month 1: galaxy starts, tests target fastAPI/uvicorn; #10823
  - [x] Month 2: run.sh does not use uwsgi; #10885
  - [ ] Month 3: Update documentation and playbooks
  - [x] Setup testing against BioBlend
 - [x] A handful of API routes fully annotated in openAPI 
   - [x] Month 1  Example routes
- [ ] History update subscriptions over websockets 
- [x] Long running background tasks  #10893
- [ ] Replacement of uWSGI with gunicorn → Admin and Deployment WGs
- [ ] SQLAlchemy 1.4 compatibility/migration; #10892 
- [ ] sqlalchemy-migrate: switch to alembic; #10369 
- [ ] SQLAlchemy: switch from classical to declarative mapping; #10901 
- [ ] Enable usable scratch storage and progress toward user base objectstores.
  - [ ] Multiple quota sources
  - [ ] Private objectstores that prevent user sharing
  - [ ] Integration test demonstrating scratch storage configuration
  - [ ] UIs for summarizing usage in useful ways → frontend
 - [x] History import & export to files plugins (→ AnVIL WG)
- [x] Performance testing at scale (w/testing and deployment teams)
- [x] Job/dataset state change optimization; #8704
- [ ] Import for user object stores (Q2)
- [ ] Remote object stores (Multi-quarter goal)
