### ISSUE TITLE
Executive summary of 2021 Q2 Backend Goals

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#11824]
*This is a draft/proposal until the backend team and the steering committee have reached an agreement.*

## Storage

- Assist deployment group in developing an end-to-end remote data example architecture - demonstration should include cloud object storage and Pulsar job handling with remote and extended metadata (so data stays remote). @mvdbeek @jmchilton 
  - Fix Pulsar to work with remote data. #11788
  - Fix various Pulsar issues with extended metadata for certain classes of tools #11813
- Implement async tool execution API based on celery (to allow for deferred file resolution) @mvdbeek #11820
- Implement exporting individual files to file source plugins (for AnVIL) @jmchilton @mvdbeek #11613
- Finish objectstore abstractions started in Q1 to enable scratch storage in Galaxy @jmchilton 
  - Implementing quotas per objectstore #10977
  - Implemented private objectstores to disable sharing, etc.. #10840
- Make substantial progress toward a prototype that migrates major portions of job setup to workers (allowing resolution of remote file URIs to be done only on workers and prevent extra copies of workflow/tool inputs, etc..). @mvdbeek, @jmchilton  #10873

## Security

- Enable IdP-based login on Main (@dannon) (https://github.com/galaxyproject/galaxy/issues/10075 ?)
- Prototype a mechanism for connecting tools to an external secretes API (e.g. custos). (@dannon ?)
- Sanitize Galaxy logs for AnVIL project (@jmchilton and possibly @assuntad23) 
   - https://github.com/galaxyproject/galaxy/issues/11807

## Architecture

- [ ] New history panel support - upgrade APIs, model layer, tests, etc.. to support new history panel as the default. @mvdbeek, @dannon #11849, #11843
- [x] Upgrade our SQL Alchemy (SA) dependency to 1.4. (@ic4f) #11737 
- [ ] Disable legacy SA behaviors to ensure we're ready for 2.0 and better support for asynchronous endpoints. (@ic4f) #10892
- [x] #12257
  - [x] Provide FastAPI apps for Tool Shed and Reports so we can drop paster/uwsgi. #11822
  - [ ] Provide example circus setup that starts the nodejs proxy we need for interactive tools. #11823
  - [x] Drop support for uWSGI mules - provide alternatives https://github.com/galaxyproject/galaxy/pull/11792
  - [ ] Migrate ansible roles to support gunicorn, etc.. during 21.05 deployment cycle (@mvdbeek).
  - [ ] Organize a documentation collaboration event with admin group on migrating all uWSGI documentation on docs and training material to newer stack (@hexylena , @mvdbeek)
- [x] Use Celery to improve history export performance @mvdbeek #11789
- [x] Assemble a tutorial on contributing to Galaxy including a backend component @ic4f @jmchilton @ #11298
- [x] Implement performance tests and continue to track down Postgres slowdowns and deadlock issues. @ic4f @mvdbeek  

Stretch Goals:

- Prototype redis integration for more robust Celery task decomposition.
- Adopt Alembic for database migrations  #10369
- Migrate more API routes to FastAPI - especially once the stack is the default and can be assumed.
- Various other ideas for utilizing remote data more efficiently from #11787
  - Allow file inputs to tools to improve potential for using remote data #11785.
  - Two-pod-like Pulsar without Kubernetes (for clusters and main) galaxyproject/pulsar#250
- Per-user objectstore #4840
- History update subscriptions over websockets
- SQLAlchemy: switch from classical to declarative mapping; #10901
- Support import and exporting workflow invocations #9024
- Implement support for GA4GH DRS @davelopez, @jmchilton #11819
