### ISSUE TITLE
Introduce tool XML attribute for minimum required Galaxy version

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#1188]
We have lots of awesome features added to the tool XML (and plans for more!) but these require minimum versions of Galaxy. (Color, `<section/>`, various new installation actions we're planning)

So! We need a way on the Toolshed side to indicate to admins that tools/packages may not function properly due to incompatible version of Galaxy and urge them to update with links to appropriate updating guides.

Tools:

``` xml
<tool id="datamash_reverse" name="Reverse" version="1.0.6" galaxy="15.10">
```

or

``` xml
        <requirements>
            <requirement type="package" version="0.7.7">pysam</requirement>
            <requirement type="galaxy" version="15.10" />
        </requirements>
```

Packages:

``` xml
<tool_dependency galaxy="15.10">
    <package name="atlas" version="3.11.11">
    ....
```

Update: According to @bgruening some of the implementation exists, with a `version` attribute on `<install />` [tags](https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_augustus_3_1/tool_dependencies.xml#L4)
## TODO
- [x] XML syntax arguments
- [ ] Update DTDs
- [ ] Toolshed (@martenson? ;) )
  - [ ] UI Hint about minimum version
  - [ ] Warning during installation

**Comment by peterjc** [comment]
I like this idea - although should the XML notation be more explicit that this is a _minimum_ version of Galaxy? Note that for tool dependencies that is the _exact_ version requested.

**Comment by hexylena** [comment]
Closing this as a version is now annotated with "tool profiles" in #1609. Remaining issues are in https://github.com/galaxyproject/galaxy/issues/2086

**Comment by martenson** [comment]
thanks @erasche !
