### ISSUE TITLE
Roadmap to FastAPI

### ISSUE THREAD

**Issue by mvdbeek** [galaxyproject/galaxy#12257]
- [x] Make run.sh use the new stack (exclusively ?): https://github.com/galaxyproject/galaxy/issues/10885
- Replace/update mentions of uwsgi as appropriate in:
  - [x] https://docs.galaxyproject.org/en/master/admin/framework_dependencies.html https://github.com/galaxyproject/galaxy/pull/13379
  - [x] https://docs.galaxyproject.org/en/master/admin/config.html @ic4f https://github.com/galaxyproject/galaxy/pull/13426 https://github.com/galaxyproject/galaxy/pull/13456
  - [x] https://docs.galaxyproject.org/en/master/admin/config_logging.html @ic4f
  - [x] https://docs.galaxyproject.org/en/master/admin/nginx.html @mvdbeek https://github.com/galaxyproject/galaxy/pull/13436
  - [x] https://docs.galaxyproject.org/en/master/admin/apache.html @mvdbeek https://github.com/galaxyproject/galaxy/pull/13439
  - [x] https://docs.galaxyproject.org/en/master/admin/scaling.html @mvdbeek https://github.com/galaxyproject/galaxy/pull/13381
  - [x] https://docs.galaxyproject.org/en/master/admin/cluster.html @mvdbeek https://github.com/galaxyproject/galaxy/pull/13440
  - [x] https://docs.galaxyproject.org/en/master/admin/jobs.html @mvdbeek https://github.com/galaxyproject/galaxy/pull/13440
  - [x] https://docs.galaxyproject.org/en/master/admin/reports.html @ic4f #13406
  - [x] https://docs.galaxyproject.org/en/master/admin/special_topics/interactivetools.html @mvdbeek
  - [x] https://docs.galaxyproject.org/en/master/admin/special_topics/interactive_environments.html (remove or merge proxy instructions with interactivetools docs) @mvdbeek https://github.com/galaxyproject/galaxy/pull/13442
  - [x] https://docs.galaxyproject.org/en/master/admin/special_topics/performance_tracking.html @mvdbeek https://github.com/galaxyproject/galaxy/pull/13441
  - [x] .k8s_ci.Dockerfile
  - [x] contrib/galaxy_supervisor.conf (drop?)
  - [x] doc/source/admin/config_logging.rst ("... identifying the uWSGI worker ID and mule ID ...")
  - [x] doc/source/admin/migrating_to_gunicorn.md (update for 22.05)
  - [x] doc/source/admin/proxy_package_layout.rst
  - [ ] doc/source/admin/scaling.md (update for 22.05)
  - [x] doc/source/admin/special_topics/interactivetools.rst ("**Native, out-of-the box support for InteractiveTools** in Galaxy via uWSGI proxying")
  - [x] lib/galaxy/config/sample/job_conf.xml.sample_advanced
  - [x] pyproject.toml
  - [x] [Ansible Galaxy](https://github.com/galaxyproject/ansible-galaxy)
  - [ ] https://training.galaxyproject.org/training-material/topics/admin/ @hexylena @natefoo @Slugger70 
- [x] Write a "why fastAPI" document https://github.com/galaxyproject/galaxy/pull/13480
- [x] Write a "how to migrate" section https://github.com/galaxyproject/galaxy/pull/13480
- [x] Create gravity schema & include sample in galaxy.yml.sample https://github.com/galaxyproject/galaxy/pull/13531
- [ ] Write a FAQ ?  
- [ ] Get together with @gmauro @hexylena @natefoo @Slugger70 and update playbooks and test servers
- [x] Remove uwsgi section from galaxy.yml, port is going to be set in gravity section
- [x] Remove paste entry points and scripts, remove `.github/workflows/api_paste.yaml` and `GALAXY_TEST_USE_UVICORN` [22.05] https://github.com/galaxyproject/galaxy/pull/13071
- [x] Remove duplicated API controllers [22.05] https://github.com/galaxyproject/galaxy/pull/13582

I will update this as we go along.

**Comment by natefoo** [comment]
>￼ https://docs.galaxyproject.org/en/master/admin/special_topics/interactivetools.html (can I convince @hexylena or @natefoo to take this on ? It may include adding the nodejs proxy to the circusd config)

Yes.

**Comment by mvdbeek** [comment]
@natefoo @dannon 
I'm working on removing all the uwsgi/paster cruft (https://github.com/galaxyproject/galaxy/compare/dev...mvdbeek:drop_wsgi_mode?expand=1) and updating run.sh, and ran into one thing I should've thought about but didn't ... do we want to provide a circusd instance per thing (galaxy, toolshed, reports) ? That seems like the only way we can just do ./run.sh or ./run_tool_shed.sh without coordinating which services to start. Or are we ok with one circusd just for Galaxy, and the rest will continue to start the process directly ? I guess I'd prefer that since it's less work, but I think we need a cron-style task for the tool shed already ... or I'll have to refactor that one toolshed cron task which I don't think has to be a cron task in the first place ...

**Comment by natefoo** [comment]
We have discussed this some on matrix, but for the record, I'm not really concerned about the other applications, fwiw. We actively discourage anyone from running a TS, so reports is the only question here, which many production servers also do not run. We could allow people to optionally run it from the Galaxy supervisor I guess?

**Comment by nsoranzo** [comment]
Q: Should we drop `merge_duplicate_keys=True` from `_order_load_path()` in `lib/galaxy/config/config_manage.py` ? It was needed because uWSGI's YAML config allowed duplicated keys. But if we drop it, I think we cannot simply ignore the `uwsgi:` section of migrated `galaxy.yml` files, but we would need to ask admins to remove it, otherwise parsing may fail.

**Comment by mvdbeek** [comment]
> But if we drop it, I think we cannot simply ignore the `uwsgi:` section of migrated `galaxy.yml` files, but we would need to ask admins to remove it, otherwise parsing may fail.

I think we should slightly restructure the file. For the conversion path I think it's fine if we rewrite the config file without the uwsgi section, for the validation part it's fine to raise a validation error.

**Comment by bgruening** [comment]
Impressive work! I guess we can close this?

**Comment by mvdbeek** [comment]
I think there's a little bit of docs left to do, I'll look over this
