### ISSUE TITLE
Executive summary of 22.01 Release Cycle Backend Working Group Goals

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#12399]
- [ ] Bring job setup decomposition from prototype to merged and deployable. 
    - xref https://github.com/galaxyproject/galaxy/compare/dev...mvdbeek:wip_remote_command_line?expand=1
    -  [ ] #10873
- [ ] https://github.com/galaxyproject/pulsar/issues/250
- [ ] Implement secrets management prototype based on planning document from 21.09 cycle. https://docs.google.com/document/d/1d-oWB8cdrIPjk60WHG4bx_S7yqA_kfzPr1Aknl_6PEs/edit?usp=sharing 
- [ ] Drop uWSGI, modern server default.
  - [ ]  #12257
  - [ ] #11823
  - [ ] Migrate ansible roles to support gunicorn, etc.. during 21.09 deployment cycle
  - [ ] Organize a documentation collaboration event with admin group on migrating all uWSGI documentation on docs and training material to newer stack
- Finish objectstore abstractions started in Q1 to enable scratch storage in Galaxy @jmchilton
   - [ ] Implementing quotas per objectstore  #10977
   - [ ] Implemented private objectstores to disable sharing, etc.. #10840
- [ ] Assist debugging tool panel view issues in production setups.
- More async Celery tasks.
  - [ ] #11820
- [ ] Implement model store plugin for RO crate support.
   - [x] https://github.com/galaxyproject/galaxy/issues/3088
   - xref https://github.com/galaxyproject/galaxy/pull/9024
- [ ] Adopt Alembic for database migrations #10369
- [ ] Prepare code base for migration to SQLAlchemy 2.0
  - [ ] Complete migration to declarative mapping #12064
  - [ ] Resolve declarative models follow-up items #12355
  - [ ] Enable SQLALCHEMY_WARN_20 (exposes legacy patterns) ([ref](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#migration-to-2-0-step-two-turn-on-removedin20warnings))
  - [ ] Resolve all RemovedIn20Warnings ([ref](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#migration-to-2-0-step-three-resolve-all-removedin20warnings))
  - [ ] Enable future flag for Engine ([ref](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#migration-to-2-0-step-four-use-the-future-flag-on-engine))
  - [ ] Enable future flag for Session ([ref](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#migration-to-2-0-step-four-use-the-future-flag-on-session))
  - [ ] Resolve any leftover SAWarnings (except those we can safely ignore)
