### ISSUE TITLE
New History Issue Tracking

### ISSUE THREAD

**Issue by guerler** [galaxyproject/galaxy#13467]
This issue keeps track of todos for the new history:

- [ ] Fix collapse/expand handling`getCurrentlyExpandedHistoryContentIds` in history watcher, fails to react to changes. Items which are expanded while the request is processing never appear.
- [ ] For histories with more than 100 datasets, the `Select all` bulk operations do not show Collection List building options in the drop-down.
- [ ] Ensure that unaccessible dataset are properly displayed
- [x] #13741
- [x] #13748
- [ ] Errors in Metadata detection are not described properly, instead the item just turns red
- [x] Apply `infinite-scrolling` to collection listing, this should be straightforward
- [x] Limit length of name shown in details component.
- [x] Populate collection details.
- [x] Style issue with extra button for hidden fields, check flex.
- [x] #13750
- [x] Text filter not working, connect correct api parameter.
- [x] Better expansion. Rare UI glitch, buttons do not move fast enough.
- [ ] Show better help? Help currently only redirects to the tool form.
- [x] Fix collection request urls
- [x] Fix collection description
- [x] Request of updated data should only ask for recently changed items, not all of them.
- [x] #13747
- [x] #13745
- [x] #13746
- [ ] Can nested datasets set tags?
- [x] #13865
- [ ] Briefly highlight content items when they are changed through the listener, optional.
- [x] #13742
- [x] Consolidate history stores
- [x] Listen to history object changes instead of changed history items
- [x] Restore tags re-adding selenium test
- [x] #13744
- [x] #13743
- [ ] The old history passes any eventual element_identifiers on (https://github.com/mvdbeek/galaxy/blob/d55f3a4598e9d226cd23ce5a1dcce27d79292159/client/src/mvc/collection/collection-model.js#L159), so you get the expected download name.

Old Issues
- [x] Collection builder in uploader not wired correctly, missing hids
- [ ] Datasets in error state freeze when requesting automated metadata detection
- [ ] Datasets in error state are not update when metadata changes

**Comment by nsoranzo** [comment]
> Lock icon for unhiding not great.

I think it's currently [eye-slash](https://fontawesome.com/icons/eye-slash?s=solid), which is also not great given that we use the "eye" icon to view the data.

**Comment by dannon** [comment]
TODO: track down duplicate requests here, as seen in this screenshot:

![image](https://user-images.githubusercontent.com/155398/157271649-4dc0c71b-5873-46fd-8570-0931a17c90a8.png)

**Comment by bgruening** [comment]
> Show better help? The help currently only redirects to the tool form.

Imho the help has nothing to do in history. Ideally, you get redirected to the tool form with the tool help in the visible area (tool from can load in the background).

**Comment by guerler** [comment]
> > Show better help? The help currently only redirects to the tool form.
> 
> Imho the help has nothing to do in history. Ideally, you get redirected to the tool form with the tool help in the visible area (tool from can load in the background).

Ok, this makes this easier and is similar to how it is currently handled. Clicking on help redirects to the tool form.

**Comment by guerler** [comment]
xref: #5472

**Comment by dannon** [comment]
Closing — the new history implementation is complete and has been the default for years. This tracking issue has served its purpose.
