### ISSUE TITLE
Use pinned requirements in the release branch

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#1432]
The dev branch uses unpinned requirements, the release should use the pinned versions.

**Comment by jmchilton** [comment]
I thought we had discussed this and decided they would both use pinned requirements until you had setup infrastructure for providing newest versions of pip packages as binary wheels?

**Comment by natefoo** [comment]
Well right now they're both using unpinned requirements, which I thought we decided to do for dev?

**Comment by natefoo** [comment]
[Part of the aforementioned infrastructure](https://github.com/galaxyproject/starforge/pull/55). With that I propose the following procedure:
1. Run `starforge wheel_updates` to determine what wheels have new versions
2. For each updated package, create a Starforge PR that updates wheels.yml with the new version
3. If the wheels are built correctly, copy them to wheels.galaxyproject.org
4. Create a Galaxy PR updating pinned-requirements.txt

These steps should be wrapped up into a script run periodically by Jenkins.

## TODO
- [ ] Create a PR comment trigger to have Jenkins perform step 3.
- [ ] The Jenkins PR builder for SF wheels should output the SHA256 sums of the things it builds for step 4.
- [ ] If testing on dev uses unpinned requirements, how do we force the versions to update? Should testing use pinned requirements instead?
- [ ] Create the script that does all of these things. It'll need to remember which package versions it has created PRs for.

**Comment by jmchilton** [comment]
Fixed with #1495

**Comment by natefoo** [comment]
We need this other stuff to be in an issue somewhere.

**Comment by jmchilton** [comment]
I'll create an issue.

**Comment by natefoo** [comment]
Appreciate it, I am upside down today.
