### ISSUE TITLE
Infrastructure for Updating Galaxy Wheels

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#1549]
Proposal from @natefoo on https://github.com/galaxyproject/galaxy/issues/1432

[Part of the aforementioned infrastructure](https://github.com/galaxyproject/starforge/pull/55). With that I propose the following procedure:
1. Run `starforge wheel_updates` to determine what wheels have new versions
2. For each updated package, create a Starforge PR that updates wheels.yml with the new version
3. If the wheels are built correctly, copy them to wheels.galaxyproject.org
4. Create a Galaxy PR updating pinned-requirements.txt

These steps should be wrapped up into a script run periodically by Jenkins.
## TODO
- [ ] Create a PR comment trigger to have Jenkins perform step 3.
- [ ] The Jenkins PR builder for SF wheels should output the SHA256 sums of the things it builds for step 4.
- [ ] If testing on dev uses unpinned requirements, how do we force the versions to update? Should testing use pinned requirements instead?
- [ ] Create the script that does all of these things. It'll need to remember which package versions it has created PRs for.

**Comment by natefoo** [comment]
We've also proposed to relocate Starforge's `wheels.yml` to Galaxy, where it would more properly live. It would mean an extra build on each PR but that build should always be green unless `wheels.yml` changed.

xref galaxyproject/starforge#43

**Comment by mvdbeek** [comment]
The current status on this is that we build wheels on https://github.com/galaxyproject/starforge-recipes/ (if we don't' manage to convince upstream to build wheels). So I'll close this one.
