### ISSUE TITLE
Galaxy should refuse to load tool if tool is too new (tool profiles)

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#2086]
- [x] document tool profiles on wiki https://github.com/galaxyproject/galaxy/issues/1609
  - http://planemo.readthedocs.io/en/latest/galaxy_changelog.html#tool-profile-version-pr-1688
- [ ] Galaxy should show warnings if galaxy is too old for a tool's specified version https://github.com/galaxyproject/galaxy/issues/1188
- [x] Galaxy should not load a tool if galaxy is too old for a tool's specified version #4382

**Comment by martenson** [comment]
> toolshed should show warnings

Galaxy should show warnings? (this is during tool installation right?)

**Comment by hexylena** [comment]
Yes, that's the correct phrasing. (Sorry, I woke up 5 minutes after the conference call started this morning)

**Comment by martenson** [comment]
@erasche sorry we woke you up and thanks for joining! :clap:

**Comment by mvdbeek** [comment]
From #4361:

This came up during the GCC (and the last GCC as well, I think ...).
Tool authors should be able to specify a minimum version of galaxy that is required to run a tool.
We already have the profile attribute, but currently galaxy instances will happily load tools regardless of the tool profile version, and the tool shed will not block or notify admins that a minimum galaxy version is required.

We can probably not rely on this retroactively, but we should have a mechanism in place so that in the future we can change certain defaults.

So what I would propose is that galaxy refuses to load a tool with a profile version higher than the running galaxy version, and that the toolshed installation process will inspect a repository for the minimum required galaxy version.

**Comment by mvdbeek** [comment]
With #4386 and #4382 I think we're pretty much there. We don't allow loading tools that are too new, and we display the minimum required galaxy version before installing the tool. We don't prevent the installation of the repository yet, but I'm not sure that's really required.

**Comment by jmchilton** [comment]
Wonderful - thanks for the additional @mvdbeek - this is great!
