### ISSUE TITLE
Testing Roadmap for 2017

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#3245]
This is a follow up from the 2016 issue at #1419. That card tracked a timeline - this one will track priorities like the main Roadmap issue.

- [x] Run Selenium tests on jenkins.galaxyproject.org against PRs. #3361 (17.01)
- [x] Run Integration tests on jenkins.galaxyproject.org against PRs. #3360 (17.01)
- [ ] Run docker-galaxy-stable tests on jenkins.galaxyproject.org against PRs. #3243 (17.01)
- [ ] Build and run deployment tests for usegalaxy.org (so Jupyter stops breaking). #3246 (17.01)
- [ ] Deploy Galaxy Community QA Infrastructure - tracked as #2642. (17.05)
  - [ ] Test Pulsar
  - [ ] Test Planemo
  - [ ] Test example tools.
  - [ ] Test example GUI test case using galaxy_selenium.
- [ ] Expand Selenium Test Coverage to every modern and important part of the GUI - #3241. (17.09)
  - [ ] #3242
- [ ] Coverage test things and track in Jenkins #2081. (17.09)
- [x] Run tests against Python 3.  (18.01)

**Comment by natefoo** [comment]
Not sure if this is the right place for it or it'd be better to open and close a new issue, but I added n6.galaxyproject.org as a Jenkins build node. There were three manual steps (everything else is in galaxyproject/infrastructure-playbook):

1. Install Jessie on n6
2. As jenkins@leeroy, `ssh n6.galaxyproject.org` to accept the host key
3. Get slave.jar from n4 and `scp slave.jar jenkins@n6:bin`

@martenson is step 3 supposed to happen automatically somehow?

**Comment by jmchilton** [comment]
Thanks a bunch @natefoo!

I've restricted n6 to only run jobs labelled explicitly for it in Jenkins. I'm going to try to get Selenium and integration tests stable for now and then once they seem to be I will re-enable the PR builder and make this box available to all Jenkins jobs.

**Comment by rbrown1422** [comment]
Good afternoon,


I am trying to get my tool shed tool to deploy in my instance of galaxy.   It does not appear to be loading the file I need to make the tool function.   It says it installed okay [green box]  and the tool appears when I click on it.

But when I run the tool the main program is not found where I tried to install it, and checking the path the file is not there


I am trying to use  the tool_dependencies.xml  to load the modules I need and I understand I must have


<requirements> <requirement type="package" version="0.9.4_9696d0ce8a962f7bb61c4791be5ce44312b81cf8">freebayes</requirement> <requirement type="package" version="0.1.18">samtools</requirement> </requirements>


QUESTION -- Does the tool_dependencies.xml go with the toolname.xml and other files in the packages repository?  And it runs when the tool is installed?  OR does it and the files in load have to be separate package?


I am looking at the site


https://wiki.galaxyproject.org/ToolShed/InstallingAndCompilingPackages


the section titled  "Installing and compiling tool dependency packages"


here is the top of my tool xml


<?xml version="1.0" encoding="UTF-8" ?>
<tool id="NGCHMheatmap" name="NGCHM Heatmap" version="4.1.2">
  <description>Create Dynamic Clustered HeatMap from Matrix and Covariate files</description>
  <requirements>
    <requirement type="package" version="4.1.2">NGCHMheatmap</requirement>
  </requirements>
  <command detect_errors="aggressive">$GALAXY_ROOT_DIR/config/plugins/visualizations/MDAheatmap/ngchm-software/heatmap.sh  '$hmname' '$hmdesc' '$inputmatrix' $rowOrderMethod $rowDistanceMeasure $rowAgglomerationMethod $columnOrderMethod $columnDistanceMeasure $columnAgglomerationMethod '$summarymethod' '$GALAXY_ROOT_DIR/tools/MDA_Heatmaps/'
    #for $op in $operations
       ${op.class_name}
       ${op.repeatinput.file_name}
       ${op.cat}
      #end for
     '$output'
 </command>


and here is my tool_dependencies.xml  file

<?xml version="1.0"?>
<tool_dependency>
 <package name="NGCHMheatmap" version="4.1.2">
    <install version="1.0">
        <actions>
        <action type="move_directory_files">
            <source>./MDAheatmap</source>
            <destination>$GALAXY_ROOT_DIR/config/plugins/visualizations/MDAheatmap</destination>
        </action>
        <action type="move_directory_files">
            <source>./TestFiles</source>
            <destination>$GALAXY_ROOT_DIR/test-data/MDAheatmap</destination>
        </action>
        <action type="shell_command">cd $GALAXY_ROOT_DIR/templates/MDAheatmap/templates</action>
        <action type="shell_command">make</action>
     </actions>
   </install>
 </package>
</tool_dependency>


I assume I am doing something wrong since the tool_dependencies does not appear to execute on tool installation.


thanks

bob

**Comment by rbrown1422** [comment]
Happy New Year,


I have a tool that I want included in the tool shed.  It depends on a visualization to be installed under  config/plugins/visualizations

I can bring in the additional visualization subdirs and files from hg or git using an action tag, but I have not found a way to get the action tags to work without having a real package.  I want to copy the visualization subdirs and files into the visualization directory when the tool is loaded from the tool shed.


I thought the package actions tags were the way to go -- but the package tag requires a real package and it appears the action tags require a package tag first.


1a. Am I missing something?   Is there a way to get the tool visualization sub-directories in place when loading my tool from the shed?

OR

1b. Can you develop a "non-package" tag that allows for only running action tags and not also look for a package?


2. Will Galaxy need to be restarted to use the new visualization when the tool is added from the tool shed?


Thanks

Bob

**Comment by martenson** [comment]
@natefoo nope, the slave.jar copying is a manual step afaik
