### ISSUE TITLE
Roadmap: Galaxy Interactive Environments

### ISSUE THREAD

**Issue by hexylena** [galaxyproject/galaxy#372]
Issue for tracking planned IE enhancements
## IEs on a remote host
- [x] IEs should be able to be launched on remote hosts #356
- [x] Should use `-P` flag of docker. Per @jmchilton's comments and some discussion on IRC, it was obvious that this is the solution we've been looking for; offload port detection to docker, avoiding any race conditions, and allowing docker on a remote host to function 100% properly. #790 
- [x] <s>It would be nice if we could somehow take advantage of the built-in job scheduling in Galaxy and the docker job scheduling available as part of that.</s> Not useful with swarm & friends, and dedicated docker preferred by admins to keep images away from jobs. 
## General IE improvements
- [x] IEs don't work with upstream proxying rules https://github.com/galaxyproject/galaxy/issues/471
- [x] ipython can be run insecurely and have port # removed from URLs https://github.com/bgruening/docker-ipython-notebook/pull/60
- [x] rstudio can remove port # from URLs https://github.com/erasche/docker-rstudio-notebook/commit/a77f025f41e63e4fb516a45bc21545fd12d5bbde
- [x] javascript needs a refactor, remove some of the requirejs + login code for ipython and make it unsecured.
- [ ] Limit/Permit subsets of users to access GIEs, especially based on regex. (For "mixed" galaxy (pub + university users), cannot allow non-university people to run GIEs)
- [x] s/IE/GIE/g
- [x] need to consider providing a base IE image
  - [x] nginx proxy, auto-kill script
- [x] Better handling of upstream proxy. Currently I'm writing apache confs that look like:
- [x] Replacement proxy
  - [x] Current proxy requires NodeJS
  - [x] Need to kill containers from proxy
    
    ``` apache
    <Location /galaxy/ipython>
    ProxyPass http://localhost:8800/galaxy/ipython/
    ProxyPassReverse http://localhost:8800/galaxy/ipython/  
    </Location>
    ```
    
    I would like to be writing apache confs like:
    
    ``` apache
    <Location /galaxy/proxy_ie>
    ProxyPass http://localhost:8800/galaxy/proxy_ie/
    ProxyPassReverse http://localhost:8800/galaxy/proxy_ie/  
    </Location>
    ```
- ~[ ] CRIU + persist to history~
- ~[ ] Inform user if pulling container/provide some interaction saying "hey, we've detected the container isn't available, so we're pulling it, please be patient". xref https://github.com/galaxyproject/galaxy/pull/1131~ Admin's job.
## IEs with multiple images

This is more of a wishlist feature... 
- [x] it'd be nice if IEs could be launched from `docker-compose.yml` files, somehow. #852  

e.g. I'm slowly working on an [Apache Zeppelin IE](http://zeppelin.incubator.apache.org/), it'd be great if I could re-use existing Zeppelin images and link an Apache Spark image, rather than having to bake everything into one.

This might involve shipping a `docker-compose.yml` in the settings folder, and applying a config variable somewhere marking this as a multi-image container. I worry about networking+picking out the correct ports and running multiple containers. Maybe we'd create a temp dir, copy in docker-compose, launch. We could do `docker-compose ps` and grab ports there maybe. This means config would have to either specially name the proxy image/we'd provide a self-killing proxy/the config would allow specifying the name of the main/proxy image.
## IE Image selection
- [x] have a single viz which allows launching N different docker images #1403 
## IEs as Tools
- ~[ ] Allow running IEs as tools OR converting them into .py + tool.xml files https://github.com/galaxyproject/galaxy/issues/1923~ It would be a nice project, but a lot of work. If someone is motivated they will discover the issue and produce something, no need to keep this issue open just for that.

## IE UX
- [ ] provide a clear 'shutdown' button for IEs (from #1586)
- [x] make the Jupyter tooltip readable (it is too long for default width of history panel) (Addressed in #1403)  
  ![screenshot 2016-01-26 12 35 49](https://cloud.githubusercontent.com/assets/1814954/12588976/6a62820e-c429-11e5-8643-db82619c0471.png)
- [x] provide a way to start Jupyter without interacting with a dataset (Addressed in #1403)
- [x] Provide a sharable link to a notebook that would start Jupyter with the NB loaded in.
- ~[ ] Provide an API to launching GIEs (?)~ Why? We need a better use case for this.

**Comment by hexylena** [comment]
@bgruening during our seminar, I noticed that we can get rid of a LOT of the port-in-url code, and the login code for IPython. The nodejs proxy uses the galaxy user's cookie for routing, so we can get rid of that.

**Comment by hexylena** [comment]
@jmchilton @bgruening open ended question/brainstorming:

We now have support for killing containers from the proxy. One problem that users will encounter nearly immediately will be the lack of a way to pause their work. Did they get interrupted for >2 minutes? Did their network drop out? Did they have to run to the loo? All of these situations will result in their container disappearing.

So, the obvious answer to that is that we should provide some "pause" functionality, or way to say "hey, I'm taking a break, please don't kill this container for at least N minutes, if I'm not back by then it's fair game".

I considered that we could implement it on the Galaxy side which got me to thinking, why not build up the full pause+restore functionality and maybe more within Galaxy? Guacamole (the VNC magic container) did this nicely with image previews for per-user VMs. Galaxy could have a section which is just dedicated to launching + using IEs? Don't know how I feel about that. It dovetails nicely with the thought that it would be nice if users could select an IE from a dropdown, and that some IEs are more tailored to taking in a whole history rather than just one dataset (IPython, Rstudio) whereas some IEs are more tailored to one dataset (iobio)

**Comment by hexylena** [comment]
Had some more thoughts on my drive today:
- can we build + submit "real" jobs without the API? Then we should move towards that. That would let us build a "real" job which:
  - contacts AMQP, sends an "I'm alive on HOST:PORT" message
  - GIE proxy picks this up and opens up routing
  - galaxy picks this up (maybe redundant with GIE proxy) and the user's "waiting..." page is listening/polling and receives that message, setting up the iframe.
- the container(s) run until done as reported by GIE proxy/traffic (I think it'll be more clear that this is just as effective as monitor_Traffic.sh going forward)
- once done, the top layers of the containers + image metadata gets tarred up + persisted as a history element
- making that re-runnable will be hella unpleasant but I think it's possible.

Will organise these into proper bullet points/plans for above later.

**Comment by mvdbeek** [comment]
@erasche regarding IEs as tools, do you have any plans on how to mark input/output files?
At least for ipython it's pretty straightforward to generate *.py.
In fact, I could make the toolfactory consume *.ipynb files ... .

**Comment by hexylena** [comment]
@mvdbeek we've had some thoughts about these in the past:
- we could add type/input annotations to the notebooks, a la [this](http://googleresearch.blogspot.com/2014/08/doing-data-science-with-colaboratory.html) and specifically the image embedded in that page
- ...

@bgruening and I have been trying to keep our priorities straight with that one, we don't want to be a toolfactory:
- we're not building permanent tools
- we're building quick one-off analyses
- we'd like for some way for people to re-run those quick analyses and iterate/share.

I think full fledged tool building may even be an anti-goal? Dunno. If you have ideas then we'd be happy to hear 'em :)

**Comment by jmchilton** [comment]
@erasche I think it is fine that full fledged tool building isn't your goal, that is a lot of room for great, transparent, interactive analysis. IE-2-tool though I would consider my primary interest in this endeavor - that would be awesome because it would fit so well with workflows.

**Comment by mvdbeek** [comment]
@erasche I remember @bgruening mentioned [this](http://googleresearch.blogspot.com/2014/08/doing-data-science-with-colaboratory.html), but I don't see how to turn it into a tool, unless you're thinking more in terms of an interactive app?

Yeah, I'm not too positive about building full tools with the toolfactory, but it's great for running things in a workflow. That's how I use it primarily in research projects, when I don't know yet if a full tool is justified.
I'll see if I can hack together a demo.

**Comment by hexylena** [comment]
@mvdbeek I'd considered those style of annotations for turning jupyter notebooks into tool XML.

@jmchilton yes, for IE-2-tool as you call it, I've mostly had a mental picture of in-notebook annotations + a tool that's dynamic enough to let you run any notebook as a tool, even if it's a bit painful. (E.g. a repeat box with an "input type" selector followed by the values to pass.)

**Comment by mvdbeek** [comment]
> @jmchilton yes, for IE-2-tool as you call it, I've mostly had a mental picture of in-notebook annotations + a tool that's dynamic enough to let you run any notebook as a tool, even if it's a bit painful. (E.g. a repeat box with an "input type" selector followed by the values to pass.)

well, except for the "annotations" being outside of the script, that's how the (admittedly not very ) interactive toolfactory works. give me the weekend, and i'll give you the demo ;)

**Comment by mvdbeek** [comment]
> @mvdbeek I'd considered those style of annotations for turning jupyter notebooks into tool XML.

Ahh, OK, that makes sense.

**Comment by martenson** [comment]
Provide a sharable link to a notebook that would start Jupyter with the NB loaded in.

added to the list

**Comment by bgruening** [comment]
Oh, yes an API endpoint to start IEs! This would also help testing them automatically.

**Comment by hexylena** [comment]
@martenson added to main checklist. Should be _dead_ easy to do since you can already launch an IE just by knowing the visualization URL to open.

**Comment by yvanlebras** [comment]
Hi everyone, not sure this is the acurate place where posting issues testing Jupyter IE on Galaxy but I'm testing some """advanced""" features and I face a first issue: When you select another kernel than Python 2, like Bash, the functionality "save the current notebook in Galaxy" did'nt work.... even if I go back to the Python 2 kernel. I continue testing it, Thank you so much for this beautiful "joujou" !!!

**Comment by bgruening** [comment]
@yvanlebras I will look at time. For the time being have a look at you PATH. There should be a `get` tool and a `put` tool that can be used by any kernel from the commandline.

**Comment by martenson** [comment]
I am going to close this issue, since the checklist seems pretty much complete and future will likely revolve around interactive tools (xref https://github.com/galaxyproject/galaxy/pull/7494)
