### ISSUE TITLE
Library system is only barely functional

### ISSUE THREAD

**Issue by nekrut** [galaxyproject/galaxy#4166]
Library system has been re-engineered, yet this process has been stalled and there are significant issues with libraries core functionality. This issue is also related to #1177 and #4069.

- [ ] Interface needs to be synced with Galaxy UI. (example: the green box announcing completion of upload in history)
- [x] Load speed. When you go to Galaxy Libraries on main it takes a considerable amount if time (20-30 sec). 
- [x] Pagination. The list is not paginated and for a new user it is impossible to see how to browse this. It turns out you need to click number 20 within this element:
![screen shot 2017-06-07 at 1 09 05 pm](https://user-images.githubusercontent.com/4291636/26891296-856755d4-4b82-11e7-92bf-1e5647e9d8c5.png)
to able to display more.
- [x] Admin interface. Libraries need to have admin interface
- [x] Need for bulk management (xref: #4069). It should be able to change permissions, datatypes, etc. in bulk
- [x] Currently it is impossible to modify dataset metadata. If you start at this screen:
![screen shot 2017-06-07 at 1 13 49 pm](https://user-images.githubusercontent.com/4291636/26891518-4ddb4624-4b83-11e7-8e97-2a03ec84afeb.png)
and actually proceed to editing, edit, and then click 'Save' you get this:
![screen shot 2017-06-07 at 1 15 25 pm](https://user-images.githubusercontent.com/4291636/26891568-76b8ea7e-4b83-11e7-85a8-b2665ecf4d3f.png)
- [ ] Using datasets directly in tools, visualizations, etc. Data should not need to be copied into history. Since the data cannot be altered without creating a new history item, the original copy should reside on the host without needing copying or counting against a user's quota. xref https://github.com/galaxyproject/galaxy/issues/4667
- [ ] all data in a data library should be pre-indexed for visualization so loading into Trackster is immediate. xref https://github.com/galaxyproject/galaxy/issues/5256
- [ ] The interface for selecting data libraries is a non-starter. I think we need a search/filtering menu based on metadata. Being able to select by different features such as data type, experiment type, cell type, species, specific keywords or proteins (e.g. for chip-seq) would be incredibly useful. I imagine something along the lines of the interface for Encode data. xref https://github.com/galaxyproject/galaxy/issues/5257

**Comment by nekrut** [comment]
@msauria @jxtx add to this issues if you have other comments

**Comment by bgruening** [comment]
xref: https://github.com/galaxyproject/galaxy/issues/1177

**Comment by martenson** [comment]
There was some follow up offline discussion right after this issue has been created and some points were cleared, please correct me if I am wrong:

* there is no need for a separate admin interface since the same UI shows admins the admin-only features
* bulk management has its own issue (https://github.com/galaxyproject/galaxy/issues/4069), so checking it here

Other comments:
* what is meant by 'synced with Galaxy UI'? Galaxy UI uses the toastr notification elsewhere (ie GIEs do)
* the system _is_ paginated (as seen on the screenshot), please clarify what is the issue
* the list of libraries slow speed on Main is linked to being an admin - we simply have too many libraries on Main for the system to handle, it needs to do backend-level pagination

* metadata modification ~~will be~~ has been enabled with https://github.com/galaxyproject/galaxy/pull/4512

The last three items seem fairly large in terms of a scope and would benefit from own explicitly described issues as I have eg very little experience with Trackster

**Comment by martenson** [comment]
bunch is finished and the rest has their owned linked issues, closing
