### ISSUE TITLE
Tool Panel - Advanced Data Selection

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#4707]
We've discussed this at team meetings a couple different times but I can't find a formal issue corresponding to our discussion other than a stray comment on #4013 ("Redesign tool inputs with an "advanced mode" drop down that allows greater flexibility in selecting inputs."). Various parts of this are mentioned in other contexts but not the specific idea of a pop-up on the tool form corresponding to an advanced mode.

New mode should allow various selection types for data / data_collection parameters including:
- [x] Selecting datasets from collections - https://github.com/galaxyproject/galaxy/issues/740.
- [x] Selecting collections from collections - https://github.com/galaxyproject/galaxy/issues/4324
- [ ] Advanced filtering - matching query language available in the history panel, access to tags, etc....
- [ ] More configurable mapping / reduction specification - https://github.com/galaxyproject/galaxy/issues/4623.
- [x] Directly from libraries (https://github.com/galaxyproject/galaxy/issues/4667).
- [ ] Directly from new uploads (https://github.com/galaxyproject/galaxy/issues/4668).
- [X] ~Slicing collections - #4013~ (I've become convinced this isn't so much a tool form problem, explicit collection reorganization is better than more complicated tool form.). 
- [x] Creating collections on-the-fly - from library folders, filtering, expressions.
- [ ] Provide interface for linked vs unlinked multi-selection (e.g. cross product vs dot product) - the backend allows this specification. https://github.com/galaxyproject/galaxy/issues/5224
- [ ] GUI for letting users choose how mapping of inputs occurs https://github.com/galaxyproject/galaxy/issues/4379

**Comment by martenson** [comment]
- selecting as collection from library

**Comment by peterjc** [comment]
Cross reference https://github.com/galaxyproject/galaxy/issues/4667 for accessing files directly from libraries

**Comment by jmchilton** [comment]
xref https://github.com/galaxyproject/galaxy/issues/4379 - I completely forgot that this is an important part of that.

**Comment by martenson** [comment]
xref https://github.com/galaxyproject/galaxy/pull/7553
