### ISSUE TITLE
History view improvements

### ISSUE THREAD

**Issue by jxtx** [galaxyproject/galaxy#5472]
# Bugs

- [x] Deletion of multiple datasets (see batching API requests) @jmchilton #5495 (finally merged into 19.05 - sorry for the delay ☹️ -John)
- [x] Saved histories load time regression (I think we are in a decent spot now -@martenson)
- [x] deleting history should send you to a recent/new history https://github.com/galaxyproject/galaxy/issues/7735
- [x] check vertical scrolling on shared grids/history panel https://github.com/galaxyproject/galaxy/issues/7736

# Enhancements

- [ ] Unify multi-history and history list
- [ ] Better feedback on job/dataset state @natefoo https://github.com/galaxyproject/galaxy/pull/7791
- [ ] allow rerun functionality on grey datasets
- [x] allow renaming of grey datasets https://github.com/galaxyproject/galaxy/issues/8417
- [x] Menu for switching between recent histories https://github.com/galaxyproject/galaxy/issues/7742

# Start Histories redesign
- [ ] Show thread for a particular tool
- [ ] Showing history as a workflow (datasets as nodes instead of tools)

**Comment by martenson** [comment]
Many of the points above are touched/solved in https://github.com/galaxyproject/galaxy/pull/8441

**Comment by dannon** [comment]
Closing — the history panel was completely rewritten in Vue with 60+ modern components, Pinia stores, and composables. The improvements tracked here have been superseded by the rewrite.
