### ISSUE TITLE
Rules Widget - Post Merge Smaller Tweaks

### ISSUE THREAD

**Issue by jmchilton** [galaxyproject/galaxy#5822]
- [X] Upload widget needs a  "Close" button for the Rule-based tab, same as on the other tabs (Regular/Composite/Collection). (Suggested by @mblue9 on #5365). (in https://github.com/galaxyproject/galaxy/pull/5823)
- [X] Upload widget needs reset button as well. (Suggested by @mblue9) (in #5823)
- [X] Instead of "Okay" button call it "Apply"  when editing rules / mapping. (Suggested by @mblue9) (#5823)
- [X] X next to mapping to remove mapping in edit mode (this is only present in the outer display of the mappings I think). (Suggested by @mblue9) (in #5823)
- [ ] Prevent "Build" until some data is present (reported by @martenson below).
- [x] Reconsider the formatting of rule definitions (namely alignment, select width) (reported by @martenson below).
- [ ] Only allow selecting text formats or tabular formats in the dataset selection list in the upload widget  (reported by @martenson below).
- [x] Make genome selector wider (reported by @martenson below).
- [ ] Better handling of the textfield as datatype of the upload widget changes (reported by @martenson below).
- [x] Allow name tags for collections:
   - [x] Textbox by name if just one collection specified, read from table like name if multiple collections.
- [x] Add drop target for text datasets. (Suggested by @mvdbeek.)
- [x] Allow reading in tags - name tags and normal tags - from rule data for individual datasets.
- [ ] New filter - contains value.
- [ ] New column adder - split on character. 
- [ ] Add checkbox requiring multiple collections to be matching - currently one can create two collections with the same structure but there is no way to force that they are the same structure and warn if they aren't. Would then implement #3916.
- [ ] Allow setting path for uploads (for admins).
- [x] Integrate with library import folder (nearly identical to FTP directory I think).
- [x] Scrolling is a mess #6100 (also reported on https://github.com/galaxyproject/galaxy/issues/6220).
- [ ] The last set of ruled uploadings might force the closure of rules currently being worked on (reported in https://github.com/galaxyproject/galaxy/issues/6220).
- [x] Add button and browser state to allow reloading last rules.

Some migrated from #5380.

**Comment by martenson** [comment]
a few observations from latest dev

* we could add validation and do not allow to click `build` until some data is present
* when switching `Load tabular data from:` the textfields should be re-initialized. e.g. now when switching from value `FTP directory` the actual contents of FTP dir remain in the field
* dataset selection for the input might want to respect the datasets format? (e.g. I shouldn't be able to select a .gz datatype)
* It could be beneficial to make genome select2 wider
![screenshot 2018-04-13 11 46 47](https://user-images.githubusercontent.com/1814954/38744664-61ae78d4-3f10-11e8-918e-48059e1b97b3.png)
* reconsider the formatting of rule definitions (namely alignment, select width) 
![screenshot 2018-04-13 11 48 08](https://user-images.githubusercontent.com/1814954/38744756-aa81f8a6-3f10-11e8-9acc-3225690b8d0d.png)

**Comment by jmchilton** [comment]
Thanks @martenson - I largely agree with these and have added them to the list above and I'll try to work on these soon. Are you sure about this bullet point though:

> when switching Load tabular data from: the textfields should be re-initialized. e.g. now when switching from value FTP directory the actual contents of FTP dir remain in the field

The lazy re-initialization right now lets you for instance switch back to the other option if you realize you shouldn't have switched it without loosing data and it lets you switch to manual data entry after selecting FTP or a dataset or manually modify what is there before bringing it into the rule builder (exclude files or rows you don't want for instance). So it looks rough I suppose but it is more functional I think. I'm not going to claim these behaviors were intentional but I wonder if they are a good accident.

**Comment by martenson** [comment]
@jmchilton +1 for re-initialization from stored state, but I think you have at least 2, but rather 3 states to store (which is fine)

**Comment by jmchilton** [comment]
> reconsider the formatting of rule definitions (namely alignment, select width)

@martenson I set a minimum width in my apply_rules branch - what were you thinking in terms of alignment? Put the column selectors below the labels, add some left-margin, etc?

<img width="1296" alt="screen shot 2018-04-16 at 10 55 14 am" src="https://user-images.githubusercontent.com/216771/38816727-ba1bd6dc-4164-11e8-997c-478ce5ba31a9.png">

**Comment by martenson** [comment]
@jmchilton I would align the column selectors and 'delete' icon to the right so you can navigate vertically between them with ease. Let me actually tinker with it a bit, I'll get back to you.

**Comment by martenson** [comment]
I am not able to scroll enough to the right to see the whole table. I would also consider adding explicit scrollbars there, on touchpad with gestures I often leave the dialogue when trying to scroll.

![screenshot 2018-04-20 16 18 48](https://user-images.githubusercontent.com/1814954/39071859-95ee256c-44b6-11e8-9d4d-fd5f736caba3.png)

**Comment by jmchilton** [comment]
@martenson Do you know how to do that? Is this https://stackoverflow.com/a/7855592 the right answer?

**Comment by martenson** [comment]
I was hoping for something like 
```css
.table {
overflow-x:scroll;
overflow-y:scroll;
overflow:scroll;
}
```

But I do not have a recent experience, will give it a try in a bit.

**Comment by hexylena** [comment]
It would be nice to be able to:

- [ ] concatenate multiple columns in one operation
- [ ] have a joining character for the concatenation (e.g. ' ', -, _)
