### ISSUE TITLE
BS4 bugs tracker

### ISSUE THREAD

**Issue by anuprulez** [galaxyproject/galaxy#5830]
This tracker collects bugs in the BS4 [branch](https://github.com/dannon/galaxy/tree/bs4).

* [x] UI issues with "run" workflow screen".

![bug6](https://user-images.githubusercontent.com/3022518/38250878-35b70f42-3750-11e8-8721-c2e795e76ab8.png)

* [x] Dataset hashtags do not have usual blue color background.

![bug7](https://user-images.githubusercontent.com/3022518/38251023-8f477cae-3750-11e8-8e42-e7735b7045ad.png)

* [x] "Back to Histories List" in the share or publish history feature loads the complete page in the central section

![bug8](https://user-images.githubusercontent.com/3022518/38253615-633e1940-3757-11e8-865b-e680855ab043.png)

* [x] Inconsistent text alignment (UI) in radio buttons for tools.

![bug9](https://user-images.githubusercontent.com/3022518/38253993-5a810532-3758-11e8-9555-50e5f26bfcfe.png)
  
* [x] Galaxy's logo and the "Galaxy" text beside is not clickable

**Comment by dannon** [comment]
@anuprulez Thanks for making this, and sorry the Github permissions didn't work more smoothly with the project board!

**Comment by bgruening** [comment]
* [x] Backdrop is missing for the upload-dialog

* [x] if data is uploaded the icon in the upload button is not centered
![grafik](https://user-images.githubusercontent.com/469983/38306592-580af704-3811-11e8-96a0-7266bf440c6b.png)

* [x] dataset details to have some heavy/big headings
![grafik](https://user-images.githubusercontent.com/469983/38306821-0d0759cc-3812-11e8-9580-9bea43f4e4e4.png)

* [x] interactive tours page
  * [x] the headings are needs some spacing 
  * [x] the buttons on the top also looks not like nice buttons they are functioning

![grafik](https://user-images.githubusercontent.com/469983/38307082-da964970-3812-11e8-8e51-6fd33f3d86fa.png)

**Comment by anuprulez** [comment]
Added Backdrop to the upload modal and fixed the size and background issues with the upload button.

**Comment by bgruening** [comment]
@anuprulez please feel free to tick them off if Dannon has merged your PR. Thanks.

**Comment by anuprulez** [comment]
@bgruening I marked off the issues I added but I can't mark off the ones you added (I cannot edit those, though I have fixed a few of them already).

**Comment by martenson** [comment]
@anuprulez I ticked the backdrop off, feel free to just comment here with what is fixed.

**Comment by anuprulez** [comment]
@martenson "if data is uploaded the icon in the upload button is not centered" item is also fixed - 5th item from the top in Bjoern's list.

**Comment by dannon** [comment]
@anuprulez Sorry, I checked that before and then it became unchecked somehow.

**Comment by dannon** [comment]
I'm going to separate this out into grouped issue cards that we can triage and work on separately.  For new issues, please report like usual and we can tag them with the (new, temporary) "BS4 Conversion Issue" tag, and add to the project board for tracking.

**Comment by dannon** [comment]
Moved upload related issues to https://github.com/galaxyproject/galaxy/issues/5850, and fixed the rest of the stuff in the primary description.

**Comment by dannon** [comment]
Ok, we've finished everything on this list that I haven't migrated to more component-specific issues.  Closing it out.  Awesome work so far, keep adding issues as necessary (new when appropriate, or tasks to component-specific issues as I've done here).
