### ISSUE TITLE
Cgroup metric plugin enhancements

### ISSUE THREAD

**Issue by natefoo** [galaxyproject/galaxy#5988]
A few enhancements to the Cgroup metrics plugin that'd be nice:

- [x] Add a db migration that increases the size of the `metric_value` column of `job_metric_numeric` to avoid having to drop larger numeric values. #5993 
- [x] Make the params to collect configurable a la the env metrics plugin. #5993 
- [ ] Collect separate metrics for the tool and set_metadata #2999
- [ ] ~Write a backgroundable script that launches before the tool and that polls for/records current memory usage with the time, for making memory-usage-over-time plots! #5994~

**Comment by natefoo** [comment]
I have the first one ready to go once #5989 is merged.
