### ISSUE TITLE
Modules to be moved to `galaxy-tool-util` package

### ISSUE THREAD

**Issue by nsoranzo** [galaxyproject/galaxy#8073]
These modules are needed by Planemo and are currently provided by `galaxy-lib`, but are not yet in `galaxy-tool-util`:

- [x] `galaxy.tools.lint` #8276
- [x] `galaxy.tools.linters` #8276
- [x] `galaxy.tools.loader_directory`
- [ ] `galaxy.tools.verify` #8284

Plus it would be nice to have the `galaxy.xsd` file presently found in:

- [x] `lib/galaxy/tools/xsd/` https://github.com/galaxyproject/galaxy/pull/8098
